### PR TITLE
GUI support for Slic3r settings

### PR DESCRIPTION
**Pull request by ra100**
Most basic slic3r settings can be set via GUI.
I added new converted slic3r profiles.
Some jQuery a css selectors are simplified.

### CODE REVIEW

**Comment by donovan6000** [comment]
Amazing work! You even made the images look better. Very impressed! :)

**Comment by ra100** [comment]
And next I'll add slic3r fill patterns. And where can I add .svg files from which I exported png icons? create folder resources or something else?

**Comment by donovan6000** [comment]
Seems like you already figured it out. All of M3D Fio's resources are accessible from the client's side at `PLUGIN_BASEURL + "m3dfio/"`. So `/static/img/image.svg` would be at `PLUGIN_BASEURL + "m3dfio/static/img/image.svg"`. Or did you mean something else?

**Comment by ra100** [comment]
I was thinking about "source" files (svg) which I used to generate fill-*.png files. Maybe it's unnecessary to have them here, I can create new repo, where I'll keep svg files and notes how to generate png from them.

**Comment by donovan6000** [comment]
It would be more complex since the [server doesn't always have write access to the any of M3D Fio's resources](https://github.com/donovan6000/M3D-Fio/issues/13), so we'd have to generate the fill images and put them in the [plugin's data folder](http://docs.octoprint.org/en/master/modules/plugin.html#octoprint.plugin.types.OctoPrintPlugin.get_plugin_data_folder) where it's guaranteed to have write access. Then we'd use [OctoPrint's blueprint API](http://docs.octoprint.org/en/master/plugins/mixins.html#octoprint.plugin.BlueprintPlugin) to have M3D Fio serve the images when they're requested since the client has no access to the data folder. The blueprint API is what caused [you to have really high RAM usage](https://github.com/donovan6000/M3D-Fio/issues/39). so I've tried to avoid using it unless it's absolutely necessary.

So if you really want to have dynamically create the fill images then we can do it, but it would definitely be simpler to just include the pre-generated images.

**Comment by donovan6000** [comment]
Also are the middle crosses in some of the fill patterns intentional or a watermark that we should remove?
fill-pattern_archimedeanchords
fill-pattern_archimedeanchords

**Comment by ra100** [comment]
Right, best way will be to have pre-generated images. I can write little script or makefile which just generates PNGs from SVGs and saves them to static/img.
And those crosses, I have cut some corners and didn't draw those images, and just used pictures from [Slic3r manual](http://manual.slic3r.org/expert-mode/infill), and used mask to have them in circle. I'll create new set of images, when I'll have more time.

**Comment by donovan6000** [comment]
I already remove all the crosses from the images and just wanted to get your approval before pushing them, so [they're all good now](https://github.com/donovan6000/M3D-Fio/commit/ace459012c27bbfa26b455f414fb89a95a0bdba5).

I'm also wondering if Slic3r's perimeters setting is actually related to the layer_height setting. If you do high quality then medium fill the resulting perimeters is 28, which seems unreasonably high. For Cura's setting [I'm related its thickness it the nozzle size](https://github.com/donovan6000/M3D-Fio/blob/devel/octoprint_m3dfio/static/js/m3dfio.js#L6298) which might be the right way to do for Slic3r's perimeters setting.

**Comment by ra100** [comment]
Number of perimeters would make more sense this way. I hoped to fined more info in [slic3r settings](https://github.com/alexrj/Slic3r/blob/7b334bf2e5315f074d408309b2256859252bd6ab/xs/src/libslic3r/PrintConfig.cpp#L719), but nothing useful there.

**Comment by ra100** [comment]
There is also [perimeter_extrusion_width](https://github.com/alexrj/Slic3r/blob/7b334bf2e5315f074d408309b2256859252bd6ab/xs/src/libslic3r/PrintConfig.cpp#L697), which can be changed. And with it simulated Cura behaviour, if we set it to 0.35.

**Pull request merged**
